from subprocess import call
# call(["python", "pncmortgage_1lakh_fixed.py"])
# call(["python", "pncmortgage_1lakh_adjustable.py"])
# call(["python", "pncmortgage_1lakh_FHA.py"])
# call(["python", "pncmortgage_1lakh_VHR.py"])
# call(["python", "pncmortgage_3lakh_Fixed.py"])
# call(["python", "pncmortgage_3Lakh_adjustable.py"])
# call(["python", "pncmortgage_3_lakh_FHA.py"])
# call(["python", "pncmortgage_3lakh_VHR.py"])
# call(["python", "pncmortgage_5lakh_Fixed.py"])
# call(["python", "pnc_5lakh_adjustable.py"])
# call(["python", "pncmortgage_5lakh_FHA.py"])
# call(["python", "pncmortgage_5lakh_VHR.py"])
# call(["python", "bank_america_mortgage.py"])
# call(["python", "boa_375000.py"])
# call(["python", "boa_625.py"])
call(["python", "synchrony.py"])
call(["python", "synchrony_make_money.py"])
call(["python", "synchrony_high_yield.py"])
# call(["python", "Wells_Fargo_Checking_Acc.py"])
# call(["python", "Wells_Fargo_Data_Deposit_Saving.py"])
